wifi: ENC[AES256_GCM,data:2KSu4HopMliYQShDy0rxTqw5Dt1gfwkqUj1TG6zP+BQl5G7PZ8LqgTQbcg99HqW2GAu4jMEwMHGXVRcLVOl5jagcjj1i4Rw=,iv:xpB0Bb9+/nrZTuYdwKzsN1RyF7X3l7a+dxtXTUsnXzw=,tag:3jLXa4DQbvofG/XA0Ozj9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sn77e7mr0kx4z36xna8has23g0q6ehwr680lrunlfg36mmvh5vyq25w3ql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU2FYOUY3WTJGUkhmKzg4
            aEVWd0ZjM2JkRWlxNlVpL3ZZYWNYdlovODF3Clo5N0NOSUZ6RUhFSVI3Qnk3V2FE
            eklERnFBSy9TalQ4OE9qUDJna0FteFUKLS0tIHl2VEhYR1NRZ3VFbzUyQzhZUjc5
            WjlLRlM2VTJBVnpKczlzTVhmUlRFQ2MKgdE4cp+6PW+Q8nEuoRHzuX5u8Ufpv/YI
            gJhUWuHmrEqspeiGiUfFUY+H4uzSDo8XAZUSUql6LpSUshYPXvh9yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14wpeg0q64cxc35xw9098gxh7r6d3vkt4yu7vn8rr4n487dyrfdfs6kjj2a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQjVESUFzV085VXJYZGNP
            UXNrWUl0djE0ZUFoU21XWS9sRWQrN1R5WURvCm80NGVTOGYvZWdRR3hHeFpMb3g3
            UkhCbGhTNmlndzNTdERucGVpR1BEWUUKLS0tIGN6bzFRbWt3UDlqeTVieVlsc0N3
            RVBwRDVIbFp5RzVJZXdsditFYnIrb0UKdGmB3CPWEomRNakYV5/ua0cMy6F2Pv7K
            cCscUTGKrODRCt0Gm+cu5S2lCbx2U2uNAPZO6ibVcV1jvjRlcwO/jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-16T23:48:57Z"
    mac: ENC[AES256_GCM,data:xaesDRd34c+vpeKARG+vjp2ic2Vvu8L+WvvqfBNK1Ruf6i0PrJfl283oAK+ofGCbIbxeRW9WEh6G4FtvHqkqi+v0Lktb1QosFSefcEPgsce2ACl5+N4Kny/KHFGvmg0oQgadPU/TS/4lC3OKz2fnmqLQnuCAZzW7PPHqxnD0L3I=,iv:PkU9I/0fOtQjgEBgR7e5mga7pOb7hTwuph8RlfnL5Jg=,tag:ceud6j/VNeoCPKZ40UsJXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
